background_images:
  - https://secure.meetupstatic.com/photos/event/6/7/8/f/highres_525326511.webp
  - https://secure.meetupstatic.com/photos/event/6/7/9/0/highres_525326512.webp
  - https://secure.meetupstatic.com/photos/event/6/7/9/7/highres_525326519.webp
  - https://secure.meetupstatic.com/photos/event/6/7/9/b/highres_525326523.webp
  - https://secure.meetupstatic.com/photos/event/2/8/2/9/highres_525850281.webp
  - https://secure.meetupstatic.com/photos/event/2/8/2/a/highres_525850282.webp
  - https://secure.meetupstatic.com/photos/event/2/8/2/c/highres_525850284.webp
  - https://secure.meetupstatic.com/photos/event/2/8/3/0/highres_525850288.webp
  - https://secure.meetupstatic.com/photos/event/2/a/6/a/highres_525850858.webp
  - https://secure.meetupstatic.com/photos/event/2/a/6/e/highres_525850862.webp
  - https://secure.meetupstatic.com/photos/event/2/a/7/0/highres_525850864.webp
  - https://secure.meetupstatic.com/photos/event/2/a/7/1/highres_525850865.webp
  - https://secure.meetupstatic.com/photos/event/2/a/7/7/highres_525850871.webp
  - https://secure.meetupstatic.com/photos/event/3/d/1/0/highres_525195632.webp
  - https://secure.meetupstatic.com/photos/event/3/c/f/e/highres_525195614.webp

gittogethers:
  description: "Delhi NCR (22nd February 2025) registrations are now closed."
  upcoming:
    - name: "Bengaluru (8th March 2025)"
      value: "Bengaluru (8th March 2025)"
    - name: "Hyderabad (8th March 2025)"
      value: "Hyderabad (8th March 2025)"
    - name: "Delhi NCR (22nd March 2025)"
      value: "Delhi NCR (22nd March 2025)"

thank_you_message: |
  Thank you for registering for GitTogether! If you're selected, we'll send you a confirmation email for this meetup.

  For queries related to GitTogethers, you can reach out to the community leader in your city. For all other queries, you can reach out to meetups@github.com 